[package]
name = "rust_lib_dutyr_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.5.0"

dutyr-shared = { path = "../../rust/crates/lib/dutyr-shared" }
