version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/src/rust"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore(cargo-deps)"
    reviewers:
      - "shymega"
    groups:
      cargo-deps:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/src/flutter"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore(pub-deps)"
    reviewers:
      - "shymega"
    groups:
      dart-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore(ci-deps)"
    reviewers:
      - "shymega"
    groups:
      gh-actions-deps:
        patterns:
          - "*"
