---
name: CI Tests Workflow - Nix

on:
  workflow_call:

jobs:
  run-tests:
    name: Nix CI tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Build all Nix packages
        run: nix build .#all
      - name: Check Flake formatting
        run: nix run nixpkgs#nixpkgs-fmt -- --check ./
      - name: Check Flake with Nix
        run: nix flake check --impure
